export const CAFE_CONSTANTS = [
  {
    id: 1,
    name: "The Coffee House",
    location: "District 1, Ho Chi Minh City",
    rating: 4.8,
    reviews: 324,
    image: "/modern-vietnamese-coffee-shop-interior.jpg",
    distance: "0.5 km",
    priceRange: "$$",
    tags: ["Wi-Fi", "Co-working", "Quiet"],
    openNow: true,
    checkIns: 1250,
    featured: true,
    lat: 10.7769,
    lng: 106.7009,
  },
  {
    id: 2,
    name: "Highlands Coffee",
    location: "District 3, Ho Chi Minh City",
    rating: 4.6,
    reviews: 892,
    image: "/cozy-cafe-plants.png",
    distance: "1.2 km",
    priceRange: "$$",
    tags: ["Wi-Fi", "Group Seating", "Outdoor"],
    openNow: true,
    checkIns: 2100,
    featured: false,
    lat: 10.7823,
    lng: 106.6958,
  },
  {
    id: 3,
    name: "Phúc Long Coffee & Tea",
    location: "District 7, Ho Chi Minh City",
    rating: 4.7,
    reviews: 567,
    image: "/traditional-vietnamese-tea-house.jpg",
    distance: "2.3 km",
    priceRange: "$",
    tags: ["Traditional", "Tea", "Desserts"],
    openNow: false,
    checkIns: 890,
    featured: false,
    lat: 10.7329,
    lng: 106.7196,
  },
  {
    id: 4,
    name: "Cộng Cà Phê",
    location: "District 1, Ho Chi Minh City",
    rating: 4.9,
    reviews: 1203,
    image: "/vintage-vietnamese-cafe.jpg",
    distance: "0.8 km",
    priceRange: "$$",
    tags: ["Vintage", "Instagram-worthy", "Local"],
    openNow: true,
    checkIns: 3400,
    featured: true,
    lat: 10.7756,
    lng: 106.7019,
  },
  {
    id: 5,
    name: "Starbucks Reserve",
    location: "District 2, Ho Chi Minh City",
    rating: 4.5,
    reviews: 445,
    image: "/premium-coffee-bar.jpg",
    distance: "3.1 km",
    priceRange: "$$$",
    tags: ["Premium", "Wi-Fi", "Meeting Space"],
    openNow: true,
    checkIns: 670,
    featured: false,
    lat: 10.7891,
    lng: 106.7217,
  },
  {
    id: 6,
    name: "L'Usine Café",
    location: "District 1, Ho Chi Minh City",
    rating: 4.8,
    reviews: 678,
    image: "/industrial-chic-cafe.jpg",
    distance: "1.5 km",
    priceRange: "$$$",
    tags: ["Boutique", "Brunch", "Design"],
    openNow: true,
    checkIns: 1560,
    featured: true,
    lat: 10.7742,
    lng: 106.7035,
  },
]